import { fal } from "@fal-ai/client";
import type { ColourPalette } from "../types/destination";

let falClient: typeof fal = fal;

/** For testing: inject a mock client */
export function setFalClient(mock: typeof fal) {
  falClient = mock;
}

export async function generatePosterImage(
  prompt: string,
  palette: ColourPalette
): Promise<string> {
  const enhancedPrompt = `${prompt}. Style: vintage travel poster, bold flat colours, clean illustration, retro typography. Dominant colours: ${palette.primary}, ${palette.secondary}, ${palette.accent}. High quality, detailed, print-ready.`;

  const result = await falClient.subscribe("fal-ai/flux/schnell", {
    input: {
      prompt: enhancedPrompt,
      image_size: "portrait_4_3",
      num_images: 1,
    },
  });

  const images = (result.data as any)?.images;
  if (!images || images.length === 0) {
    throw new Error("No image generated by fal.ai");
  }

  return images[0].url;
}
